import { database,seed,runtime,apiError,sameOrigin,logEvent,readJson } from '@/lib/server';
import { defaultConfig,validConfig,scenarios } from '@/lib/contracts';
export async function GET(){try{await seed();const db=database();const [devices,sessions,events,count]=await Promise.all([db.prepare('SELECT id,name,online,rssi,config,version,created_at AS createdAt FROM devices ORDER BY created_at,id').all(),db.prepare('SELECT id,device_id AS deviceId,text,source,latency,confidence,duration,bytes,created_at AS createdAt,scenario FROM sessions ORDER BY created_at DESC LIMIT 2000').all(),db.prepare('SELECT id,type,device_id AS deviceId,detail,created_at AS createdAt FROM events ORDER BY created_at DESC LIMIT 200').all(),db.prepare('SELECT COUNT(*) AS count FROM sessions').first<{count:number}>()]);return Response.json({devices:devices.results.map(d=>({...d,config:JSON.parse(String(d.config))})),sessions:sessions.results,events:events.results,sessionCount:count?.count??0,asrConfigured:!!runtime().ASR_URL,now:Date.now()},{headers:{'Cache-Control':'no-store'}});}catch{return apiError('The console could not reach its database. Please retry.',503);}}
export async function POST(request:Request){try{if(!sameOrigin(request))return apiError('Origin not allowed',403);if(Number(request.headers.get('content-length'))>16000)return apiError('Request too large',413);const b=await readJson(request);await seed();const db=database();
 if(b.action==='addDevice'){const name=typeof b.name==='string'?b.name.trim():'';if(name.length<2||name.length>60)return apiError('Use a device name between 2 and 60 characters.');const id=`tinywake-${crypto.randomUUID().slice(0,8)}`;const inserted=await db.prepare('INSERT INTO devices (id,name,online,rssi,config,version,created_at) SELECT ?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM devices) < 50').bind(id,name,1,null,JSON.stringify(defaultConfig),1,Date.now()).run();if(!inserted.meta.changes)return apiError('This workspace supports up to 50 simulator devices.',409);await logEvent('DEVICE_ADDED',id,'Simulator device registered.');return Response.json({id}, {status:201});}
 if(typeof b.deviceId!=='string')return apiError('Select a device.');const device=await db.prepare('SELECT * FROM devices WHERE id = ?').bind(b.deviceId).first();if(!device)return apiError('Device not found.',404);
 if(b.action==='setOnline'){if(typeof b.online!=='boolean')return apiError('Invalid connection state.');await db.prepare('UPDATE devices SET online = ? WHERE id = ?').bind(b.online?1:0,b.deviceId).run();await logEvent(b.online?'SIMULATOR_CONNECTED':'SIMULATOR_DISCONNECTED',b.deviceId,'Simulator connection state changed.');return Response.json({ok:true});}
 if(b.action==='saveConfig'){if(!validConfig(b.config))return apiError('Configuration values are outside the allowed range.');if(!Number.isInteger(b.version))return apiError('Configuration version required.');const result=await db.prepare('UPDATE devices SET config = ?, version = version + 1 WHERE id = ? AND version = ?').bind(JSON.stringify(b.config),b.deviceId,b.version).run();if(result.meta.changes===0)return apiError('Configuration changed elsewhere. Refresh before saving.',409);await logEvent('CONFIG_SAVED',b.deviceId,'Configuration saved for simulator.');return Response.json({ok:true,version:Number(b.version)+1});}
 if(b.action==='simulate'){if(typeof b.key!=='string'||!/^[a-zA-Z0-9-]{8,80}$/.test(b.key))return apiError('A valid request key is required.');if(typeof b.phrase!=='string'||b.phrase.trim().toLowerCase().replace(/[.!?]/g,'')!=='hey loki')return apiError('Wake phrase rejected. The complete phrase “Hey Loki” is required.',422);const s=scenarios.find(s=>s.id===b.scenario);if(!s)return apiError('Unknown scenario.');const id=`sim-${b.key}`;const existing=await db.prepare('SELECT * FROM sessions WHERE id = ?').bind(id).first();if(existing&&(existing.device_id!==b.deviceId||existing.scenario!==s.id))return apiError('Request key already used for a different scenario.',409);if(!existing){if(!device.online)return apiError('This simulator is offline. Connect it before running a scenario.',409);const config=JSON.parse(String(device.config));if(s.confidence<config.wakeThreshold)return apiError('Sample confidence is below the device wake threshold.',422);const last=await db.prepare("SELECT MAX(created_at) AS time FROM sessions WHERE device_id = ? AND id LIKE 'sim-%'").bind(b.deviceId).first<{time:number|null}>();if(last?.time&&Date.now()-last.time<config.cooldownMs)return apiError('The device is cooling down. Try again shortly.',429);}const result=await db.prepare('INSERT OR IGNORE INTO sessions (id,device_id,text,source,latency,confidence,duration,bytes,created_at,scenario) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,b.deviceId,s.text,'simulated',s.latency,s.confidence,s.duration,Math.round(s.duration*32000),Date.now(),s.id).run();const canonical=await db.prepare('SELECT * FROM sessions WHERE id = ?').bind(id).first();if(!canonical||canonical.device_id!==b.deviceId||canonical.scenario!==s.id)return apiError('Request key already used for a different scenario.',409);if(result.meta.changes)await logEvent('SIMULATION_COMPLETE',b.deviceId,'Scenario completed. All audio and timing values are simulated.');return Response.json({id,text:canonical.text,source:'simulated',latency:canonical.latency,duration:canonical.duration,confidence:canonical.confidence});}
 return apiError('Unknown action.');
 }catch{return apiError('The request could not be completed. Check your inputs and retry.');}}
