import { apiError,database,logEvent,runtime,sameOrigin,seed } from '@/lib/server';
export async function POST(request:Request){
 if(!sameOrigin(request))return apiError('Origin not allowed.',403);
 const config=runtime();if(!config.ASR_URL)return apiError('ASR server is not configured. No audio has been sent.',503);
 try{const url=new URL(config.ASR_URL);if(url.protocol!=='https:')return apiError('ASR server must use HTTPS.',503);}catch{return apiError('ASR server configuration is invalid.',503)}
 const deviceId=new URL(request.url).searchParams.get('deviceId');if(!deviceId)return apiError('Select a simulator device.');
 try{await seed();const db=database();const device=await db.prepare('SELECT online FROM devices WHERE id = ?').bind(deviceId).first();if(!device)return apiError('Device not found.',404);if(!device.online)return apiError('Connect the selected simulator first.',409);
 const max=1924096;if(Number(request.headers.get('content-length'))>max)return apiError('Audio must be no longer than 60 seconds.',413);const reader=request.body?.getReader();if(!reader)return apiError('Audio file is empty.');let length=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();return apiError('Audio must be no longer than 60 seconds.',413)}chunks.push(value)}const audio=new Uint8Array(length);let offset=0;for(const chunk of chunks){audio.set(chunk,offset);offset+=chunk.length}if(length<44)return apiError('Invalid or empty WAV file.');const view=new DataView(audio.buffer),str=(n:number,l:number)=>new TextDecoder().decode(audio.subarray(n,n+l));if(str(0,4)!=='RIFF'||str(8,4)!=='WAVE'||view.getUint32(4,true)+8!==length)return apiError('Upload a valid RIFF WAV file.');let sampleRate=0,channels=0,bits=0,format=0,dataSize=0;
 for(let p=12;p+8<=length;){const size=view.getUint32(p+4,true);if(p+8+size>length)return apiError('Truncated WAV file.');if(str(p,4)==='fmt '){if(size<16)return apiError('Invalid WAV format.');format=view.getUint16(p+8,true);channels=view.getUint16(p+10,true);sampleRate=view.getUint32(p+12,true);bits=view.getUint16(p+22,true)}if(str(p,4)==='data')dataSize+=size;p+=8+size+(size%2)}if(format!==1||sampleRate!==16000||channels!==1||bits!==16)return apiError('Use 16 kHz, mono, 16-bit PCM WAV audio.');if(dataSize<3200||dataSize%2||dataSize/32000>60)return apiError('Audio must be between 0.1 and 60 seconds.');
 const start=performance.now();const response=await fetch(config.ASR_URL,{method:'POST',headers:{'Content-Type':'audio/wav',...(config.ASR_TOKEN?{Authorization:`Bearer ${config.ASR_TOKEN}`}:{})},body:audio,redirect:'error',signal:AbortSignal.timeout(45000)});if(!response.ok){await logEvent('ASR_FAILED',deviceId,`ASR server returned HTTP ${response.status}.`);return apiError('The ASR server could not transcribe this audio. Try again.',502)}
 const payload=await response.json() as {text?:unknown};if(typeof payload.text!=='string'||!payload.text.trim()||payload.text.length>10000)return apiError('The ASR server returned no usable transcript.',502);const latency=Math.round(performance.now()-start),id=`asr-${crypto.randomUUID()}`;await db.prepare('INSERT INTO sessions (id,device_id,text,source,latency,confidence,duration,bytes,created_at,scenario) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,deviceId,payload.text.trim(),'measured',latency,null,dataSize/32000,length,Date.now(),'recorded_audio').run();await logEvent('ASR_COMPLETE',deviceId,`Recorded audio transcribed in ${latency} ms. Raw audio not stored.`);return Response.json({id,source:'measured',latency});
 }catch(e){const message=e instanceof Error?e.name:'';if(message==='TimeoutError'||message==='AbortError')return apiError('ASR request timed out. Your audio was not saved.',504);return apiError('Audio processing failed. Check your ASR connection and try again.',502)}
}
