'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { AudioLines,ArrowRight,ArrowUpRight,Box,ChevronRight,CircleHelp,Clock3,Cpu,Download,Gauge,LayoutDashboard,Plus,Radio,Settings2,ShieldCheck,Terminal,X } from 'lucide-react';
import { Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from '@/components/ui/sheet';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import { Status,MetricCards,ActivityChart,Monitor,Pipeline,Fleet,SessionTable,exportSessions } from '@/components/console-ui';
import { ConfigView,DevicesView,HistoryView,LiveView,ModelsView,PerformanceView,LogsView,DocsView } from '@/components/console-views';
import type { ConsoleData,Device,Session } from '@/lib/contracts';
const nav=[{name:'Overview',icon:LayoutDashboard},{name:'Devices',icon:Cpu},{name:'Live transcription',icon:AudioLines},{name:'Session history',icon:Clock3},{name:'Performance',icon:Gauge},{name:'Models',icon:Box}];
const views=[...nav.map(n=>n.name),'Configuration','Event logs','Documentation'];
const descriptions:Record<string,string>={Overview:'Listen locally. Understand remotely.',Devices:'One place for every voice at the edge.','Live transcription':'Follow a conversation from wake word to understanding.','Session history':'Every interaction, with the details that matter.',Performance:'Understand the cost of every conversation.',Models:'Small models. A meaningful difference.',Configuration:'Fine-tune how your devices listen.','Event logs':'A clear record of what happened.','Documentation':'A practical guide to your TinyWake workspace.'};
export default function Home(){
 const [view,setView]=useState('Overview'),[data,setData]=useState<ConsoleData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[adding,setAdding]=useState(false),[name,setName]=useState(''),[busy,setBusy]=useState(false),[range,setRange]=useState('24h'),[selectedDevice,setSelectedDevice]=useState<Device|null>(null),[selectedSession,setSelectedSession]=useState<Session|null>(null),[activeDevice,setActiveDevice]=useState('tinywake-001');
 const loaded=useRef(false);
 const navigate=useCallback((next:string)=>{if(!views.includes(next))return;setView(next);location.hash=encodeURIComponent(next);setNotice('');setError('');window.scrollTo({top:0,behavior:'instant'})},[]);
 const refresh=useCallback(async()=>{const r=await fetch('/api/console');const result=await r.json() as any;if(!r.ok)throw new Error(result.error||'Could not refresh the console.');setData(result);loaded.current=true;return result as ConsoleData},[]);
 const action=useCallback(async(body:Record<string,unknown>)=>{const r=await fetch('/api/console',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json() as any;if(!r.ok)throw new Error(result.error||'This action could not be completed.');try{await refresh()}catch{setError('Your change was saved, but the console could not refresh. It will retry shortly.')}return result},[refresh]);
 useEffect(()=>{let active=true;const load=()=>refresh().catch(e=>{if(active)setError(e.message)});load();const interval=setInterval(load,10000);const sync=()=>{let n='Overview';try{n=decodeURIComponent(location.hash.slice(1))||n}catch{};if(views.includes(n))setView(n)};sync();window.addEventListener('hashchange',sync);return()=>{active=false;clearInterval(interval);window.removeEventListener('hashchange',sync)}},[refresh]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'tinywake_navigate',description:'Open a TinyWake console view.',inputSchema:{type:'object',properties:{view:{type:'string',enum:views}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input:any){if(!input||!views.includes(input.view))throw new Error('Unknown view');navigate(input.view);return {view:input.view}}},{name:'tinywake_create_simulator',description:'Create and save a simulator device in this private workspace.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:2,maxLength:60}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input:any){if(typeof input?.name!=='string'||input.name.trim().length<2||input.name.trim().length>60)throw new Error('Name must be 2–60 characters');const result=await action({action:'addDevice',name:input.name});navigate('Devices');return result}}];for(const tool of tools){try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort()},[action,navigate]);
 async function addDevice(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await action({action:'addDevice',name});setAdding(false);setName('');setNotice('Your simulator is connected and ready.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function openLive(id?:string){if(id)setActiveDevice(id);setSelectedDevice(null);navigate('Live transcription')}
 const selected=selectedDevice?data?.devices.find(d=>d.id===selectedDevice.id):null;
 return <SidebarProvider style={{'--sidebar-width':'238px'} as React.CSSProperties}><Sidebar><SidebarHeader className="brand"><div className="brand-symbol"><AudioLines size={25}/></div><span>TinyWake<span className="brand-dot">.</span></span></SidebarHeader><SidebarContent className="nav-content"><div className="workspace"><span className="workspace-avatar">T</span><div>TinyWake workspace<small>Personal workspace</small></div></div><p className="nav-label">PLATFORM</p><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.name}><SidebarMenuButton className="nav-button" isActive={view===n.name} onClick={()=>navigate(n.name)}><n.icon/><span>{n.name}</span>{n.name==='Live transcription'&&<i className="nav-live"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><p className="nav-label manage">MANAGE</p><SidebarMenu>{[{name:'Configuration',icon:Settings2},{name:'Event logs',icon:Terminal}].map(n=><SidebarMenuItem key={n.name}><SidebarMenuButton className="nav-button" isActive={view===n.name} onClick={()=>navigate(n.name)}><n.icon/><span>{n.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="sidebar-bottom"><div className="edge-note"><ShieldCheck size={20}/><strong>Private by design</strong><p>Your audio stays on the edge.<br/>Until you say the word.</p></div><button className="doc-button" onClick={()=>navigate('Documentation')}><CircleHelp size={17}/>Documentation<ArrowUpRight size={15}/></button><div className="profile"><span className="profile-avatar">TW</span><div>TinyWake Lab<small>Development environment</small></div><span className="version">v1.0</span></div></SidebarFooter></Sidebar>
 <div className="app-main"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger className="mobile-menu"/><span>Workspace</span><ChevronRight size={13}/><span>{view}</span></div><div className="topbar-right"><span className="environment"><i/>Simulator workspace</span><span className="header-divider"/><span className="avatar-small">TW</span></div></header>
 <main className="page-content"><div className="page-heading"><div><div className="eyebrow">EDGE-TO-CLOUD INTELLIGENCE</div><h1>{view}</h1><p>{descriptions[view]}</p></div><div className="heading-actions"><Button variant="outline" className="button-secondary" disabled={!data} onClick={()=>data&&exportSessions(data.sessions,data.devices)}><Download size={15}/>Export report</Button><Button className="button-primary" onClick={()=>{setError('');setAdding(true)}}><Plus size={17}/>Add device</Button></div></div>
 <div className="simulation-banner"><Radio size={15}/><span><strong>Demo environment</strong> · Simulated devices and sample sessions. Hardware metrics are not yet measured.</span><span className="banner-tag">SIMULATED DATA</span></div>
 {error&&<div className="feedback error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="feedback" role="status">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {!data?<div className="loading-console"><h2>Connecting to your workspace…</h2>{error&&<Button variant="outline" onClick={()=>refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Retry connection</Button>}<div className="stats-grid">{[0,1,2,3].map(n=><Skeleton className="h-36" key={n}/>)}</div></div>:<>
 {view==='Overview'&&<><MetricCards data={data}/><div className="main-grid"><ActivityChart sessions={data.sessions} range={range} setRange={setRange} now={data.now}/><Monitor device={data.devices.find(d=>d.online)} onOpen={()=>openLive(data.devices.find(d=>d.online)?.id)}/></div><Pipeline/><section className="fleet-section"><div className="section-heading"><h2>Your devices<span className="count-badge">{data.devices.length}</span></h2><button className="text-button" onClick={()=>navigate('Devices')}>View all devices<ArrowRight size={14}/></button></div><Fleet devices={data.devices.slice(0,4)} onSelect={setSelectedDevice}/></section><section className="panel sessions-panel"><div className="panel-heading"><h2>Recent sessions</h2><button className="text-button" onClick={()=>navigate('Session history')}>View session history<ArrowRight size={14}/></button></div><SessionTable sessions={data.sessions.slice(0,4)} devices={data.devices} onSelect={setSelectedSession}/></section></>}
 {view==='Devices'&&<DevicesView data={data} onSelect={setSelectedDevice}/>}
 {view==='Live transcription'&&<LiveView data={data} activeDevice={activeDevice} setActiveDevice={setActiveDevice} action={action} refresh={refresh} onSession={setSelectedSession}/>}
 {view==='Session history'&&<HistoryView data={data} onSelect={setSelectedSession}/>}
 {view==='Performance'&&<PerformanceView data={data}/>}
 {view==='Models'&&<ModelsView/>}
 {view==='Configuration'&&<ConfigView data={data} action={action} activeDevice={activeDevice} setActiveDevice={setActiveDevice}/>}
 {view==='Event logs'&&<LogsView data={data}/>}
 {view==='Documentation'&&<DocsView/>}
 </>}
 <footer className="page-footer"><span><span className="tiny-dot"/>TinyWake platform · Development</span><span>Listen locally. Understand remotely.</span></footer></main></div>
 <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Add a device</DialogTitle><DialogDescription>Create a software node to explore the TinyWake workflow.</DialogDescription></DialogHeader><form onSubmit={addDevice} className="form-stack"><label htmlFor="device-name">Device name</label><Input id="device-name" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Kitchen Node" required minLength={2} maxLength={60} autoFocus/><div className="info-box"><Cpu size={19}/><div><strong>Software simulator</strong><p>Ready instantly. No microphone or hardware required.</p></div></div>{error&&<p role="alert" className="inline-error">{error}</p>}<Button type="submit" className="button-primary" disabled={busy}>{busy?'Adding device…':'Add simulator'}<Plus size={15}/></Button></form></DialogContent></Dialog>
 <Sheet open={!!selectedDevice} onOpenChange={o=>{if(!o)setSelectedDevice(null)}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{selected?.name??'Device details'}</SheetTitle><SheetDescription>{selected?.id}</SheetDescription></SheetHeader>{selected&&<div className="sheet-body"><Status muted={!selected.online}>{selected.online?'Listening':'Offline'}</Status><div className="detail-list">{[['Device type','Software simulator'],['Wake phrase','Hey Loki'],['Model profile','hey-loki-v1 (sample)'],['RSSI',selected.rssi===null?'Not measured':`${selected.rssi} dBm (simulated)`],['Configuration',`Version ${selected.version}`],['Physical hardware','Not connected'],['CPU / RAM','Not yet measured']].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><Button className="button-primary" disabled={!selected.online} onClick={()=>openLive(selected.id)}>Run a scenario<ArrowRight size={15}/></Button><Button variant="outline" onClick={()=>{setActiveDevice(selected.id);setSelectedDevice(null);navigate('Configuration')}}>Configure device</Button><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await action({action:'setOnline',deviceId:selected.id,online:!selected.online})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{selected.online?'Disconnect simulator':'Connect simulator'}</Button><p className="helper">Connection state is controlled by the simulator. It does not indicate a physical ESP32 heartbeat.</p></div>}</SheetContent></Sheet>
 <Sheet open={!!selectedSession} onOpenChange={o=>{if(!o)setSelectedSession(null)}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Session details</SheetTitle><SheetDescription>{selectedSession?.id}</SheetDescription></SheetHeader>{selectedSession&&<div className="sheet-body"><Status>{selectedSession.source==='simulated'?'Simulated scenario':'Measured ASR'}</Status><blockquote className="session-quote">“{selectedSession.text}”</blockquote><div className="detail-list">{[['Device',data?.devices.find(d=>d.id===selectedSession.deviceId)?.name??selectedSession.deviceId],['Time',new Date(selectedSession.createdAt).toLocaleString()],['Wake confidence',selectedSession.confidence===null?'Not measured':`${Math.round(selectedSession.confidence*100)}% (simulated)`],['Audio duration',`${selectedSession.duration}s`],['ASR latency',`${selectedSession.latency} ms`],['Audio size',`${(selectedSession.bytes/1000).toFixed(1)} KB`],['Audio stored','No']].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="helper">{selectedSession.source==='simulated'?'This scenario uses preset text, confidence, timings, and audio volume. No microphone audio was processed.':'The ASR response, received byte count, and server processing time are measured. Wake detection was manually simulated.'}</p><Button variant="outline" onClick={()=>data&&exportSessions([selectedSession],data.devices)}><Download size={15}/>Export this session</Button></div>}</SheetContent></Sheet>
 </SidebarProvider>
}


